accounts:
  - name: alice
    coins: ["20000state", "200000000stake"]
  - name: bob
    coins: ["10000state", "100000000stake"]
  - name: carol
    coins: ["10000state", "100000000stake"]
  - name: dom
    coins: ["10000state", "100000000stake"]
  - name: eve
    coins: ["10000state", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["80000000state", "100000stake"]
